// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuUyEW_6AA4saDxD-MPkww_yAKwrHxBGg',
    appId: '1:215104120920:web:e1b861de947ab39adbc22d',
    messagingSenderId: '215104120920',
    projectId: 'saheli-d22e4',
    authDomain: 'saheli-d22e4.firebaseapp.com',
    storageBucket: 'saheli-d22e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFX_QQvKw5slT-Q7nmJ9-msSpWV1CLPMU',
    appId: '1:215104120920:android:48a5bd3b0bb59835dbc22d',
    messagingSenderId: '215104120920',
    projectId: 'saheli-d22e4',
    storageBucket: 'saheli-d22e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9S3EfeGFZIbBMfCPQMDUt4hC4ZxhHxiw',
    appId: '1:215104120920:ios:40b4f91556ece7c8dbc22d',
    messagingSenderId: '215104120920',
    projectId: 'saheli-d22e4',
    storageBucket: 'saheli-d22e4.appspot.com',
    iosClientId: '215104120920-8sqqdemadfmaofbci133dhn6149e4u7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gsochome',
  );
}
